// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4zTiSVAM4oqgPyO_UypBKa9JaQ5cWhP0',
    appId: '1:285859933702:web:8bdd3290cf4160c2b8dd87',
    messagingSenderId: '285859933702',
    projectId: 'nymble-assessment',
    authDomain: 'nymble-assessment.firebaseapp.com',
    storageBucket: 'nymble-assessment.appspot.com',
    measurementId: 'G-P0EC7BZY8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-MwWNYoE0l-sYk0nrxGBtr9-khWvIK0M',
    appId: '1:285859933702:android:2a8d260daca2ffffb8dd87',
    messagingSenderId: '285859933702',
    projectId: 'nymble-assessment',
    storageBucket: 'nymble-assessment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBdTgzbOWlCgXfQJmrM-egGXgOhOj_Ro0',
    appId: '1:285859933702:ios:423e8109127c7397b8dd87',
    messagingSenderId: '285859933702',
    projectId: 'nymble-assessment',
    storageBucket: 'nymble-assessment.appspot.com',
    iosBundleId: 'com.example.musicPlayer',
  );
}
